apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinite-ttt-app
  namespace: infinite-ttt
  labels:
    app: infinite-ttt-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: infinite-ttt-app
  template:
    metadata:
      labels:
        app: infinite-ttt-app
    spec:
      containers:
        - name: infinite-ttt-app
          image: shayanzzzz/infinite-tic-tac-toe:latest
          ports:
            - containerPort: 80
          env:
            - name: VITE_SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: supabase-credentials
                  key: VITE_SUPABASE_URL
            - name: VITE_SUPABASE_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-credentials
                  key: VITE_SUPABASE_KEY
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20

