apiVersion: v1
kind: Secret
metadata:
  name: supabase-credentials
  namespace: infinite-ttt
type: Opaque
stringData:
  VITE_SUPABASE_URL: "https://ffwgyfveetrjshgefxdx.supabase.co"
  VITE_SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmd2d5ZnZlZXRyanNoZ2VmeGR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3NDE3MzgsImV4cCI6MjA1NTMxNzczOH0.Qw8-grPCnKrHvV5NJ_bKlGv0w7ePIU9QgsQsmJ7coQw"

