apiVersion: v1
kind: Service
metadata:
  name: infinite-ttt-service
  namespace: infinite-ttt
  labels:
    app: infinite-ttt-app
spec:
  type: ClusterIP
  selector:
    app: infinite-ttt-app
  ports:
    - name: http
      port: 8080
      targetPort: 80
